INSERT INTO TBL_PROFESSIONAL(NAME, HOURLY_RATE, AREA) VALUES ('Paulo', '20', 'TI');
INSERT INTO TBL_PROFESSIONAL(NAME, HOURLY_RATE, AREA) VALUES ('Rodrigo', '20', 'WEB');
INSERT INTO TBL_PROFESSIONAL(NAME, HOURLY_RATE, AREA) VALUES ('Sophia', '20','UX');